version: '3'

services:
  app:
    build: .
    container_name: eventors
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/eventors
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: eventors-db
    tty: true
    env_file: .env
    environment:
      - POSTGRES_DB=$PSG_DB
      - POSTGRES_USER=$PSG_USER
      - POSTGRES_PASSWORD=$PSG_PASSWORD
    volumes:
      - eventors-pgdata:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: iniciando-django-pgadmin
  #   tty: true
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@user.com
  #     - PGADMIN_DEFAULT_PASSWORD=123456
  #   ports:
  #     - "9000:80"

volumes:
  eventors-pgdata:
    external: true