databases:
  - name: appevent
    databaseName: appevent
    user: lbdev

services:
  - type: web
    name: appevent
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn umveventos.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: appevent
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
